### ISSUE TITLE
Boss，新版是不是去掉了 origin.type了？ 我个人觉得还是要保留。

### ISSUE THREAD

**Issue by ihadai** [think2011/localResizeIMG4#1]
Boss，新版是不是去掉了 origin.type了？ 我个人觉得还是要保留。
因为在选择文件后，可以判断是否选择的为图片文件，否则则 return，否则选择一个 非图片文件，插件就会报错， 并没有进入 catch 方法里。 而是插件报出错误：Uncaught Error: 加载图片文件失败，并终止了js运行。

**Comment by think2011** [comment]
处于优化的目的去掉了。

临时解决的话，你可以通过 this.files[0].type 来获取，其实this.files[0]也就是 origin。

另外type这个判断并不准确，某些图片根本不存在这个值，如果你不需要担心这个问题的话，直接通过

```html
<input type="file" accept="image/*" capture="camera" />
```
判断更方便。


下次更新会加上 origin 字段。

**Comment by ihadai** [comment]
好的，多谢

**Comment by think2011** [comment]
@ihadai  已更新版本

**Comment by ihadai** [comment]
:+1:    好的，多谢，Boss幸苦了。
