### ISSUE TITLE
魅族，华为等手机使用百度浏览器时无响应

### ISSUE THREAD

**Issue by fanyCeltic** [think2011/localResizeIMG4#10]
lrz()方法不执行，走不下去，请您抽时间看一下呗

**Comment by isszz** [comment]
这个BUG在上个版本也存在...我反馈后更新了版本我以为解决了- -....结果百度浏览器也还是不行

**Comment by think2011** [comment]
恩，会找个机会测试一下。

**Comment by think2011** [comment]
似乎解决了问题了，访问在线demo试试吧，当前是`4.2.1`版本。
