### ISSUE TITLE
android 4.2/4.4 原生浏览器不支持

### ISSUE THREAD

**Issue by yzhuomaoy** [think2011/localResizeIMG4#13]

**Comment by think2011** [comment]
具体是什么表现呢？ 控制台有什么内容输出？

**Comment by yzhuomaoy** [comment]
问题出现在 URL.createObjectURL(file)

**Comment by think2011** [comment]
@yzhuomaoy 这个问题我没能在模拟环境中测试出来。

如果看到demo中底下的4张图片都是显示正常的，那么可能点击上传输入的文件有问题。

**Comment by yzhuomaoy** [comment]
测试都不是在微信浏览器, 是android自带的.
Android4.2扫出来只显示图片名, 说明在压缩过程出错.
Android4.4无法点击上传, 这个是platform的bug,  所以我用了ImagePicker插件

**Comment by think2011** [comment]
@yzhuomaoy 我更新了demo，在demo中如果有出错会提示出来，有空请帮忙试试截张图出来吧。

**Comment by yzhuomaoy** [comment]
下面这是Android4.2, Android4.4 (emulator)是我上面截图的错误

![image](https://cloud.githubusercontent.com/assets/1639012/9685597/e592f074-5351-11e5-8063-799f69f6084d.png)

**Comment by chaoyuebeyondgit** [comment]
android 4.3原生浏览器也是这样的，得不到base64码。

**Comment by think2011** [comment]
@chaoyuebeyondgit  @yzhuomaoy 
请问你们用的具体是什么设备和系统版本呢？

**Comment by chaoyuebeyondgit** [comment]
联想a788t(发布时间2013.12.19)，系统Android4.3。

**Comment by think2011** [comment]
似乎解决了问题了，访问在线demo试试吧，当前是`4.2.1`版本。

**Comment by chaoyuebeyondgit** [comment]
![screenshot_2015-09-09-15-37-06](https://cloud.githubusercontent.com/assets/14052160/9830511/281e213a-5964-11e5-874d-c9e1a9681392.png)
大神，联想a788t(发布时间2013.12.19)，系统Android4.3，这个现在可以获得base64码，我扫了下二维码怎么发现有的图片越压缩却越大了。

**Comment by chaoyuebeyondgit** [comment]
第一个是oprea下压缩正常，之前不可以现在可以了，第二个是Android4.2原生浏览器，压缩出现了比原来还大的情况。
![screenshot_2015-09-09-15-43-54](https://cloud.githubusercontent.com/assets/14052160/9830538/3a78526e-5965-11e5-89a2-0db72541dfc4.png)


大神，怎么破？

**Comment by chaoyuebeyondgit** [comment]
![screenshot_2015-09-09-15-51-18](https://cloud.githubusercontent.com/assets/14052160/9830564/015812d4-5966-11e5-9e92-99ed52cfc450.png)

**Comment by think2011** [comment]
对了，@chaoyuebeyondgit 麻烦试一下吧，因为截图中的UA版本号刚好断行了，我写的判断是 `Android/4.3 Release..` 不知道正不正确。

**Comment by chaoyuebeyondgit** [comment]
谢谢大神，刚刚用原生Android4.3可以正常压缩了。谢谢大神！！！！！Perfect!!!!!!!!!!!

**Comment by yzhuomaoy** [comment]
@think2011 谢谢, 刚看到回复, 现在回复晚了, 我4.2是用了华为畅玩3C, Android4.2.1, 现在测试OK.
有时间我再试试Android4.4的, Android4.4我是用了emulator测试, 图片上传用了插件ImagePicker(cordova)
