### ISSUE TITLE
插件中rst函数执行顺序问题。大神求救！！！！！

### ISSUE THREAD

**Issue by chaoyuebeyondgit** [think2011/localResizeIMG4#14]
lrz(that.files[0], {
        width: 1024
    })
        .then(function (rst) {
            var img        = new Image(),
                div        = document.createElement('div'),
                p          = document.createElement('p'),
                sourceSize = toFixed2(that.files[0].size / 1024),
                resultSize = toFixed2(rst.base64Len * 0.8 / 1024),
                scale      = parseInt(100 - (resultSize / sourceSize * 100));
               console.log("rst.base64....."+rst.base64);//后打印出来
            p.style.fontSize = 13 + 'px';
            p.innerHTML      = '源文件：<span class="text-danger">' +
                sourceSize + 'KB' +
                '</span>，压缩后<span class="text-success">' +
                resultSize + 'KB (省' + scale + '%)' +
                '</span> ';

            div.className = 'col-sm-6';
            div.appendChild(img);
            div.appendChild(p);

            img.onload = function () {
                that.parentNode.appendChild(div);
            };

            img.src = rst.base64;

            return rst;
        });
		 console.log("11....."+11);//先打印出来
为什么执行的顺序是先执行后面的 console.log("11....."+11);//先打印出来
在执行.then(function (rst) 中的 console.log("rst.base64....."+rst.base64);//后打印出来
怎么能使其顺序执行，大神求救啊，项目需要！！！！！

**Comment by think2011** [comment]
[http://liubin.github.io/promises-book/#introduction](http://liubin.github.io/promises-book/#introduction)

了解一下promise吧，掌握之后能够写出很有条理的代码。

上面的问题，你可以把 `console.log...` 的操作放到 `then()` 里面去执行。

**Comment by chaoyuebeyondgit** [comment]
您好，这个顺序执行怎么改呢？麻烦吗？谢谢大神！求指导啊！！！

**Comment by chaoyuebeyondgit** [comment]
lrz那里面代码实在看不太懂，是菜鸟，这两天主要急着用。大神帮忙解决一下吧，谢谢！！！！

**Comment by chaoyuebeyondgit** [comment]
我现在的需求是顺序得到base64码，然后传到服务器，大神指点迷津！！！！！！

**Comment by think2011** [comment]
抱歉，太忙了，过了几天了，你应该找到方法了吧，其实[wiki](https://github.com/think2011/localResizeIMG4/wiki)里就有例子

**Comment by chaoyuebeyondgit** [comment]
您好，那个顺序问题我没有解决，我利用您demo中的index.js中的监听事件，基本解决了。现在我是用jQuery mobile进行的移动开发，我页面只引用了lrz.bundle.js文件，发现在ios上测试的时候，能得到图片的base64码，可是放到Android上却不行，ios测试一切正常，Android调用lrz不起作用（难道Android与ios所引用的文件有所区别？），大神指点迷津！！！谢谢!!!!
