### ISSUE TITLE
ios测试正常，Android没反应，得不到base64码，大神指点！！！！！！谢谢

### ISSUE THREAD

**Issue by chaoyuebeyondgit** [think2011/localResizeIMG4#15]
我利用您demo中的index.js中的监听事件，基本解决了我想要的每个图片base64码，发到服务器。现在我是用jQuery mobile进行的移动开发，我页面只引用了lrz.bundle.js文件，发现在ios上测试的时候，能得到图片的base64码，可是放到Android上却不行，ios测试一切正常，Android调用lrz不起作用（难道Android与ios所引用的文件有所区别？看到demo那么多js文件，只需引用一个lrz.bundle.js？吗），大神指点迷津！！！谢谢!!!!

**Comment by think2011** [comment]
恩，仅需引入一个文件，其他文件会按需加载， android下出问题有可能按需加载出错了。

**Comment by think2011** [comment]
近期打算写一个不按需加载的js文件

**Comment by chaoyuebeyondgit** [comment]
我用联想手机A788t 扫了下二维码，发现Android （4.3），自带浏览器与手机自带oprea浏览器不行，而手机下载的QQ浏览器是可以的，这个可能是不兼容导致的吗？还有，是不是我的web目录下必须有dist目录，且目录必须有有两个chunk.js,与一个lrz.buddle.js。您demo中的其他js文件要不要也放在我的web目录下如您demo中的src中的js文件。感谢您的回复！！！！！

**Comment by chaoyuebeyondgit** [comment]
大神您好！我用联想A788t手机（android 4.3）原生自带浏览器,与opera浏览器均不能得到base64码，用华为荣耀与小米4手机测试一切正常。今天看到您更新了代码，便用二维码扫了一下，发现联想A788t手机（android 4.3）原生自带浏览器,与opera浏览器均压缩不到图片。而qq浏览器（Android）却能得到，切页面报错如下：
![screenshot_2015-09-01-10-00-04](https://cloud.githubusercontent.com/assets/14052160/9679439/1323628e-5321-11e5-8680-9486f52f2661.png)
![screenshot_2015-09-01-10-06-46](https://cloud.githubusercontent.com/assets/14052160/9679446/25578f5c-5321-11e5-93ee-ed6104570441.png)

**Comment by think2011** [comment]
@chaoyuebeyondgit 
Hi，据我了解，有一些旧版本的android手机自身的浏览器特性就不完善，例如你发的`联想A788t`的截图报错来看是找不到 `click`方法，一般的浏览器如果能找到`dom`元素，那么元素一定会有存在`click`方法的。

另外在前年根据反馈和实测，有部分旧版本android手机，响应 `input:file`的结果也各不同.. 这类的情况.. 似乎无解..

**Comment by think2011** [comment]
@chaoyuebeyondgit 要用到的文件都在 `dist`里，其他不需要，增加了一个说明文件，可以看看。

**Comment by chaoyuebeyondgit** [comment]
大神您好，总感觉是代码与原生浏览器不兼容的问题。有机会您可以用不同版本Android的原生浏览器测试一下试试，#13楼好像也有这种问题。谢谢大神！！！

**Comment by think2011** [comment]
似乎解决了问题了，访问在线demo试试吧，当前是`4.2.1`版本。
