### ISSUE TITLE
能不能写一个只提供ios拍照并上传照片的版本

### ISSUE THREAD

**Issue by spursy** [think2011/localResizeIMG4#16]
由于刚入开发不久，大神的代码看的不是太懂。能不能写个只针对ios开发的版本。

**Comment by spursy** [comment]
谢谢

**Comment by think2011** [comment]
Hi, 关于你的需求，仅需引用核心文件`lrz.bundle.js`即可，其他文件请保留。

在IOS7.12以上，仅有上面的文件就能实现需求了，发现低于这个版本才会异步再载入兼容文件。

关于android的代码文件，是绝对不会再载入的。

**Comment by spursy** [comment]
Hi ，我只需要引入lrz.bundle.js,那么其他的文件还需要加载到项目中吗？有没有时间写个很小的ios的Demo。
能不能推荐本前端技术的入门书籍，您的前端代码基本看不懂呀。谢谢

**Comment by think2011** [comment]
其他文件保留，需要的时候（IOS版本低于7.12）才会自动加载，因为你的需求只是IOS，android相关的代码不会被载入的。

前端的书的话，刚入门可以看看 《JavaScript高级程序设计》, 关于我写的代码，可以看《JavaScript异步编程》。

辅助编译用的是`gulp 和 webpack`这个工具。

**Comment by think2011** [comment]
@spursy  demo的话，https://github.com/think2011/localResizeIMG4/wiki 这里有

**Comment by spursy** [comment]
Hi,我按照您昨天的方法可以实现了。谢谢您的耐心指导。

由于我点击choose file的标签时出现的是拍照还是去相册是英文的，我要改写成中文，以及拍摄或是从相册中拿到的照片显示在特定的image标签上。请问您我该如何改写您的js。

**Comment by spursy** [comment]
function upload () {
    lrz(this.files[0])
        .then(function (rst) {
            // 处理成功会执行
        })
        .catch(function (err) {
            // 处理失败会执行
        })
        .always(function () {
            // 不管是成功失败，都会执行
        });
});
我参照这个js方法，当我从相册或摄像头获得照片后我可以进如update方法，但是不能进入lrz类里面的方法。（注：我是可以获得图片的）
