### ISSUE TITLE
js问题？

### ISSUE THREAD

**Issue by spursy** [think2011/localResizeIMG4#17]
function upload () {
lrz(this.files[0])
.then(function (rst) {
// 处理成功会执行
})
.catch(function (err) {
// 处理失败会执行
})
.always(function () {
// 不管是成功失败，都会执行
});
});
我参照这个js方法，当我从相册或摄像头获得照片后我可以进如update方法，但是不能进入lrz类里面的方法。（注：我是可以获得图片的）

**Comment by think2011** [comment]
用在线demo测试能成功吗？ 有可能哪里出错了，如果是PC上出现的问题，请将控制台的错误截图出来吧（如果有的话）。

**Comment by spursy** [comment]
![60aa05f3-4d22-4e4f-92ab-c63aa5c4429c](https://cloud.githubusercontent.com/assets/11460991/9831634/d4270afa-5991-11e5-9431-fc60bd1abec5.png)
这是我的项目，我是可以点击file标签可以调用摄像头或是相册的。
我也是可以进入update方法的，但是不能进入
lrz(this.files[0])
.then(function (rst) {
// 处理成功会执行
})
.catch(function (err) {
// 处理失败会执行
})
.always(function () {
// 不管是成功失败，都会执行
});
});

**Comment by think2011** [comment]
单独看上面的代码没能看出什么，或许你可以单独写个例子发到我的邮箱。

**Comment by think2011** [comment]
如果有问题，打开这个issue。
