### ISSUE TITLE
在iphone下拍摄完照片后，页面自动刷新或闪退了

### ISSUE THREAD

**Issue by pimmyye** [think2011/localResizeIMG4#2]
在iphone下拍摄完照片后，页面自动刷新或闪退了，请问是什么原因

**Comment by pimmyye** [comment]
压缩需要占用很多内存吗？

**Comment by pimmyye** [comment]
直接选择图片，没有这个问题

**Comment by think2011** [comment]
[http://think2011.github.io/localResizeIMG4/test/](http://think2011.github.io/localResizeIMG4/test/)

在上面的demo中试过吗？

我试过iphone4 IOS7，没能重现问题。

或许不一定是内存的原因，可能在某些情况某些特性引起的崩溃。

但目前为止我都没能重现这个错误。

**Comment by mhbseal** [comment]
安卓下为什么根据orientation来drawImage呢，不晓得这边是为了兼容什么，我这边之前写过一个，貌似直接类似于你的ctx.drawImage(img, 0, 0, resize.w, resize.h)也没啥问题。

**Comment by think2011** [comment]
@mhbseal 
在PC和IOS下，经过canvas过来的图片其实是没旋转好的，似乎在android下会自动调整成正确的方向。

但不确定，所以还引入的exif来判断方向，如果android能确定自动旋转的话，大概还能省10-20k+的文件请求(exif.js)。

**Comment by think2011** [comment]
@mhbseal 你把手机倒过来拍摄一张照片，然后不作任何处理，复制原件到PC上去直接 ctx.drawImage 就会发现问题了。

**Comment by pimmyye** [comment]
http://think2011.github.io/localResizeIMG4/test/

这个demo试过了，拍完照后刷新了页面

**Comment by mhbseal** [comment]
之前写过一个和你这个类似（有bug），但是没你这个全面，但是看完你的源码下来有几个问题：
1.exif这个库是用来获取orientation的，但是Android的貌似html5通过相册取图片的时候已经旋转成正确方向了，所以canvas画的时候不用再去根据orientation去drawImage了，PC和IOS还是需要的，已测试。
2.jpeg_encoder_basic这个库，是解决toDataURL无压缩？安卓原生浏览器下可能是不需要的（已测试），引入这个是解决微信里面无压缩的？还是？具体不清楚...
3.还有个在IOS上超过w:3264,h:2448无法生成base64，这个有出处吗？另外这块代码处理貌似也有点问题！

**Comment by mhbseal** [comment]
@pimmyye 这个6plus safari下，确实有浏览器爆掉的问题。其他ios，我们这边测试没发现过这种情况。

**Comment by think2011** [comment]
@mhbseal  
1. 恩，那可以确定android可以不引入exif了，低版本的android有试过吗？
2.  jpeg_encoder_basic 解决4.5（或者4.3?）以下的android输出无压缩的情况。
3. 这个我测试过，存在什么问题了？

P.S：似乎微信有自带的压缩接口，如果接下来时间不忙的话，考虑集成进去好了。


@pimmyye 据说6+有这个问题，我有空会核实下。

**Comment by think2011** [comment]
@pimmyye  
用6+ IOS8.1模拟器测试没能重现问题。
另外从你描述来看，底下的4张图都没能造成闪退，问题应该是出在拍摄完 - 进入lrz处理之间发生的错误。

但是.. 木有6+ 可以测试。 ：（

**Comment by dwandw** [comment]
IP 6+ 64G
safari & 微信内置浏览器 都没有重现这个问题
@pimmyye 具体型号可以说一下

**Comment by PeakFish** [comment]
应该是 内存爆了， 后台应用多开点，选大图片好像就这样，浏览器退出了，又自己打开就刷新页面了。网上搜了搜 好多这样的问题。
