### ISSUE TITLE
RequireJS GET 2.chunk.js 404

### ISSUE THREAD

**Issue by kenberkeley** [think2011/localResizeIMG4#20]
RequireJS的main.js文件：  
```javascript
require.config({
    paths: {
        jquery: '/lib/jquery.min',
        underscore: '/lib/underscore-min',
        backbone: '/lib/backbone-min',
        upload: '/lib/upload/lrz.bundle' // 压缩图片工具
    },
    shim: {
        underscore: {
            exports: '_'
        },
        backbone: {
            deps: ['underscore', 'jquery'],
            exports: 'Backbone'
        },
        upload: {
            exports: 'lrz'
        }
    }
});
```
  
我把四个文件都放在/public/lib/upload目录下，如下图：  
![image](https://cloud.githubusercontent.com/assets/13287948/9980835/4e55bc60-5fda-11e5-9980-39156a147baa.png)
  
之后使用的时候就报错如下图：  
![image](https://cloud.githubusercontent.com/assets/13287948/9980842/8d37a236-5fda-11e5-9b34-cb096127037f.png)
  
既然它让我把2.chunk.js放在那里，于是。。。我就把四个文件都直接放在/public/lib目录下，虽然很不规范，但是木有报错。。。不过由于我有强迫症，所以还是厚脸皮发帖求教，还望作者大大指点。。。

**Comment by think2011** [comment]
@kenberkeley  Hi，这是我的问题，构建用的工具是webpack，我因为会自动兼容 requirejs 或者 seajs的，实际上并没用。

稍晚点我修复一下。

**Comment by kenberkeley** [comment]
想不到作者大大那么快就回复我了，让我内牛满面有木有！！！呜呜呜。。。  
对了，其实我还想说，这个插件对手机硬件性能要求很高，旧手机基本没法用。。。

**Comment by think2011** [comment]
不是大大，其实很菜的说..

是因为某些旧手机系统底层不支持部分HTML5特性才导致这样的，相比之前，现在好太多了，相信明年就不会再是问题了。

**Comment by kenberkeley** [comment]
那么我设置的压缩率是0.1，请问这是不是原因？
