### ISSUE TITLE
js异步编程导致并发时串图

### ISSUE THREAD

**Issue by mylightworld** [think2011/localResizeIMG4#21]
由于源码中使用了诸如Promise的异步编程技术，在实际使用过程中发现同时在上传图片的用户的图片相串了，a的图的数据跑到b的，b的图片数据跑到c的，而且串图的概率非常高。

如果只有一个人在线或者自己测试，一般不会发现此问题，因为异步编程没有影响。

还在研究代码，大家有没有遇到类似的问题？

**Comment by think2011** [comment]
@mylightworld 能发下代码片段吗？

**Comment by think2011** [comment]
如果还有问题，打开这个issue。
