### ISSUE TITLE
压缩完，图片变的更大了是怎么回事？？？？

### ISSUE THREAD

**Issue by okooo00** [think2011/localResizeIMG4#22]
。。。。

**Comment by kenberkeley** [comment]
其实并没有变得更大，是根本没有压缩。  
我在舍友的三星Note 10.1(2014)上测试，选择图片文件压缩。  
  
发现压缩后的图片的rst.base64Len要比原图的file.size要大。  
但是上传到服务器之后，还是原本的分辨率以及大小。

**Comment by kenberkeley** [comment]
![12a82c539cc90338176efb0458cdd491](https://cloud.githubusercontent.com/assets/13287948/10213572/6ee80e50-6841-11e5-8e95-9ca3ea10a76b.jpg)

**Comment by kenberkeley** [comment]
![2015-10-01 13 37 16](https://cloud.githubusercontent.com/assets/13287948/10213580/8b0b3a3a-6841-11e5-8968-ae9fcc837120.png)

**Comment by kenberkeley** [comment]
最后还是贴上代码比较好说话
![qq20151001-1 2x](https://cloud.githubusercontent.com/assets/13287948/10213678/cb61b31a-6842-11e5-854a-53eb7120db75.png)

**Comment by think2011** [comment]
@okooo00 @kenberkeley 
Hi，请用手机访问一下在线demo，然后截图出来吧，似乎是没有提取到特征，所以能成功应用到Android的压缩补丁。

**Comment by kenberkeley** [comment]
再次用舍友的平板测试了一下。。。。发现。。。一切正常。。。我擦。。。我擦。。。

**Comment by think2011** [comment]
如果还有问题请重新开启。
