### ISSUE TITLE
电脑上测试可以上传预览，手机上不行，怎么破，求大神指点。

### ISSUE THREAD

**Issue by lincolon** [think2011/localResizeIMG4#24]
直接手机访问你提供的demo http://think2011.github.io/localResizeIMG4/test/可以上传，我下载到本地运行就不行了，都快哭了

**Comment by think2011** [comment]
有出错提示弹出吗？

请用有问题的手机访问一下demo，然后截图出来吧。

**Comment by think2011** [comment]
如果还有问题请重新开启。
