### ISSUE TITLE
为什么图片只有一半  苹果ios6  (不是苹果6)

### ISSUE THREAD

**Issue by Messilimeng** [think2011/localResizeIMG4#26]
![74af26c0-6d82-11e5-9b36-b50245131708](https://cloud.githubusercontent.com/assets/12272166/10360043/3b8334d8-6dd0-11e5-992f-8ae06ea04fb6.png)

**Comment by think2011** [comment]
@Messilimeng 将有问题的照片【原件】发到我的邮箱 452125301.hzplay@gmail.com 吧，需要调试一下。
