### ISSUE TITLE
希望图片小于设定宽度的时候不要被拉伸

### ISSUE THREAD

**Issue by yuu2lee4** [think2011/localResizeIMG4#27]
比如我设置640px宽  如果原图小于640px  那么就保持原图大小就好了  然后希望增加一个大小的选项 就说说设定图片压缩后的一个大小。。其实上传图片这个参数应该是最重要的(当然如果图片本身就小于设定值就不应该被压缩)。。。。

**Comment by think2011** [comment]
恩，需要做的。
