### ISSUE TITLE
上次报告并发时会串图的问题被删掉了？

### ISSUE THREAD

**Issue by mylightworld** [think2011/localResizeIMG4#28]
多人同时上传图片时，a的图会串到b的图中，代码如下：

![qq 20151013114156](https://cloud.githubusercontent.com/assets/1798758/10445022/b2167510-719f-11e5-9f63-749584fd9bc1.png)

/*
function lrzNewImageChanged(dataInJson) {
    //加载中……
    showLoading();

    dataInJson = dataInJson || {};
    type = initParam(dataInJson.type, 'secondhand');
    count = initParam(dataInJson.count, 6);

    lrz(dataInJson.e.files[0], {
        width: 1024, quality: 0.7
    })
        .then(function (rst) {
            //上传到后端进行保存
            //alert(JSON.stringify(rst));
            $.ajax({
                url: '/' + type + '/imgup',
                type: "post",
                data: { base64String: rst.base64, type: "base64" },
                dataType: 'text',
                success: function (data, text) {
                    //alert(data);

                    //关闭加载中……
                    hideLoading();

                    var imgPath = data.substring(1, data.length - 1);

                    var imgPaths = $("#ImagePaths").val();
                    imgPaths = imgPaths != "" ? imgPaths + "," + imgPath : imgPaths + imgPath;
                    $("#ImagePaths").val(imgPaths);

                    var html = "<li><a href='javascript:;' onclick='deleteImage(this," + count + ");'><img class='img-item' src='" + imgPath + "'/></a></li>";
                    $(html).insertBefore(".image-item-add-wrap");

                    if (imgPaths.split(',').length >= count) {
                        $(".image-item-add-wrap").addClass("notshow");
                    }
                }
            });

        });
    //ie8以下不兼容
    //.catch(function (err) {
    //    // 处理失败会执行
    //    taost({ message: err });

    //    //关闭加载中……
    //    hideLoading();
    //})
    //.always(function () {
    //    // 不管是成功失败，都会执行
    //});
}
*/

**Comment by think2011** [comment]
#21 在这里，需要发一下代码才能判断问题。

**Comment by think2011** [comment]
我猜是 .success 后面做的显示图标冲突了，基于性能的原因，异步请求之后，当前rst.base64是被删除或者替换了的。

那么你可以在 .then 之后就做图片显示处理，如果异步请求出错了，然后再删除图片来提醒用户重新上传。
