### ISSUE TITLE
lrz(this.files[0])显示Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by qz2374876** [think2011/localResizeIMG4#29]
为什么在上传图片后就会提示这个，在lrz(this.files[0])处，chrome浏览器

**Comment by think2011** [comment]
麻烦写一下出错demo或者代码吧，看描述判断不了问题。

**Comment by qz2374876** [comment]
<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default3.aspx.cs" Inherits="Default3" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>无标题页</title>
    <script type="text/javascript" src="localResizeIMG4-master/dist/lrz.bundle.js"></script>
</head>
<body>
    <form id="form1" runat="server">
    <input onchange="upload()" type="file" accept="image/*" />
    </form>
</body>
</html>
<script type="text/javascript">
function upload () {
    lrz(this.files[0])
        .then(function (rst) {
            // 处理成功会执行
        })
        .catch(function (err) {
            // 处理失败会执行
        })
        .always(function () {
            // 不管是成功失败，都会执行
        });
};
</script>

**Comment by qz2374876** [comment]
我发你邮箱了，麻烦你看一下

**Comment by think2011** [comment]
没有收到邮件噢？ 我的邮箱是 452125301.hzplay@gmail.com

**Comment by qz2374876** [comment]
发过去了

**Comment by think2011** [comment]
恩，收到了，找个时间看一下。

**Comment by qz2374876** [comment]
好的谢谢

**Comment by think2011** [comment]
上下文指向错误了，试试这样的写法

```html
<input id="file" type="file" accept="image/*" />
```

```js
document.querySelector('#file').addEventListener('change', function () {
	lrz(this.files[0])
        .then(function (rst) {
            // 处理成功会执行
            console.log(rst)
        })
        .catch(function (err) {
            // 处理失败会执行
        })
        .always(function () {
            // 不管是成功失败，都会执行
        });
});
```

**Comment by qz2374876** [comment]
这样可以了，谢谢你
