### ISSUE TITLE
在线代码压缩的时候，有一个链式编程的语法编译不通过，[ERROR] :missing name after . operator

### ISSUE THREAD

**Issue by erhu1999** [think2011/localResizeIMG4#3]
你好，在线代码压缩的时候，有一个链式编程的语法编译不通过。
比如说在http://tool.oschina.net/jscompress
网站中压缩以下代码会报错([ERROR] 4:17:missing name after . operator)：

lrz(file, {quality:0.6})
        .then(function(results){
            
        }).catch(function (err) {
            
        });

**Comment by think2011** [comment]
这个压缩工具不支持关键字的压缩。

代码需要这样写

```js
lrz()['catch'](func)...
```
