### ISSUE TITLE
在安卓微信下拍照以后，拍照界面无法点击确认当前图片

### ISSUE THREAD

**Issue by qianzhangsheng** [think2011/localResizeIMG4#30]
我觉得应该是安卓自身问题，不知道大家有没有遇到

**Comment by think2011** [comment]
http://think2011.github.io/localResizeIMG4/test/

在这里测试也是一样的结果嘛？ 如果不是的话，就删减代码，查查其他原因。

**Comment by qianzhangsheng** [comment]
一样的效果，测试环境是安卓4.0的小米手机

拍完照片以后，选择确认没有反应

**Comment by qianzhangsheng** [comment]
解决了，是小米miui问题，更新到最新就可以了

**Comment by think2011** [comment]
恩，太好了。
