### ISSUE TITLE
安卓微信浏览器上传图片时提示只能上传SD卡中的文件

### ISSUE THREAD

**Issue by qz2374876** [think2011/localResizeIMG4#31]
手机上用微信浏览demo页面，上传图片提示只能上传SD卡中的文件，实际测试发现所说的SD卡指的是手机自身存储介质而非外插的SD卡，也就是说只能上传手机自身存储介质里的图片，SD卡的图片无法上传

**Comment by think2011** [comment]
http://www.wufoo.com/html5/types/14-file.html

是由设备系统自己决定的，讨厌的是Android各个系统表现还不一样。

上面是一个 input:file 响应设置，你可以用设备测试一下看看。

**Comment by qz2374876** [comment]
试过了都不行，那只能这样了
