### ISSUE TITLE
图片压缩时间比较慢

### ISSUE THREAD

**Issue by striveCj** [think2011/localResizeIMG4#34]
作者大大你好，就是用lrz的时候想先压缩然后再显示，压缩时间大概在6到10秒之间波动太慢了，不知道有没有什么好的解决办法？

**Comment by think2011** [comment]
android设备吗？ 还是IOS6？  遇到过部分android和IOS6会卡那么久，正常情况是1秒内就完成了的。

**Comment by striveCj** [comment]
是Android设备，test也用了差不多也是6秒左右低端安卓机更慢，ios的还没测试

**Comment by think2011** [comment]
目前为止我测试到的就只有IOS6的iphone5会有情况，直到后来升级IOS7之后就没再出现了。

系统级的问题无法解决..
