### ISSUE TITLE
webpack引入模块为空

### ISSUE THREAD

**Issue by Iamlars** [think2011/localResizeIMG4#36]
var lrz = require('./lrz.js');
//当使用webpack加载lrz模块时，lrz为空对象。

在文件最后加入下面代码，才能正常导入：
module.exports = function () {
    return window.lrz();
};

**Comment by think2011** [comment]
![qq20151019-1 2x](https://cloud.githubusercontent.com/assets/3961388/10574531/23b1d190-7689-11e5-872b-a5866e30f23a.png)

咦，不会吧？ 源码中另外一个文件是你说的方式引用的，麻烦再确认一下。

**Comment by Iamlars** [comment]
可能是代码压缩之后，module关键字被替换成了变量e造成的。我使用的是https://github.com/think2011/localResizeIMG4/blob/master/dist/lrz.bundle.js

**Comment by think2011** [comment]
webpack 生成后的代码似乎是不再有 AMD|CMD 规范的了，具体我没有仔细研究过。

既然你使用webpack，应该直接引用源代码，因为webpack最终会帮你打包的。

**Comment by Iamlars** [comment]
好的，谢谢~只是书写的时候需要require进来。
