### ISSUE TITLE
微信客户端中无法压缩

### ISSUE THREAD

**Issue by zjlcmpg** [think2011/localResizeIMG4#4]
MG3很好用，电脑CHROME、手机UC上都可以压缩，但在安卓微信客户端上没压缩多少，甚至体积还变大了。MG4也是这个问题，麻烦有空修复下~

**Comment by think2011** [comment]
顺便附上以下内容吧：
```
平台：微信
设备：iPhone5 IOS7
问题：问题描述呗..
```

**Comment by zjlcmpg** [comment]
![434261699764979704](https://cloud.githubusercontent.com/assets/13843963/9321716/975a37cc-459c-11e5-8a9d-b3df9d9af4c6.jpg)
如图，安卓微信客户端扫描页面上的二维码进入LRZ4 DEMO，随便选择一张照片压缩，结果文件体积反而变大了。

**Comment by zjlcmpg** [comment]
![screenshot_2015-08-27-15-42-30](https://cloud.githubusercontent.com/assets/13843963/9515237/ac4dc530-4cd2-11e5-8e6d-1eaafae696d5.png)
作者不好意思，我又来了。
红米NOTE2用微信浏览器压缩有问题，压缩后的图片还是严重偏大，手机：红米NOTE2移动版，系统：MIUI6.7.3.0(安卓5.0.2)，微信版本：6.2.4。
我有点怀疑是微信浏览器的问题，因为包括上面反映的NEXUS5在内，UC浏览器里转换都很正常，唯独微信浏览器有问题。

**Comment by think2011** [comment]
@zjlcmpg  我更新了版本了，有空的话请打开demo，然后截个图出来吧，demo增加了一些调试信息。

**Comment by zjlcmpg** [comment]
![n5](https://cloud.githubusercontent.com/assets/13843963/9660284/6de894b8-5287-11e5-9f7d-c68327c287e6.png)
![rm2](https://cloud.githubusercontent.com/assets/13843963/9660333/bb9d31d2-5287-11e5-8e6c-160840bb4f9d.png)
Nexus5 和 红米NOTE2都截了。

**Comment by think2011** [comment]
@zjlcmpg 尝试解决了一下，再去demo试试吧！

**Comment by zjlcmpg** [comment]
![screenshot_2015-09-03-22-26-50](https://cloud.githubusercontent.com/assets/13843963/9661041/71ebcc8e-528b-11e5-8592-6494a7054c17.png)
![screenshot_2015-09-03-22-27-01](https://cloud.githubusercontent.com/assets/13843963/9661114/d61c51ec-528b-11e5-9591-fb0f1faf580b.png)

**Comment by think2011** [comment]
不知道是QQ浏览器的问题，还是android的问题，总之引入了jpeg算法，看起来是解决了。

**Comment by zjlcmpg** [comment]
非常感谢~~~~
另外，我感觉是微信的原因，因为之前出现这个问题的时候我用手机UC和手机CHROME试过，都好的。
