### ISSUE TITLE
lrz.bundle.js、1.chunk.js 和 2.chunk.js 他们仨能在一起么？

### ISSUE THREAD

**Issue by yuekcc** [think2011/localResizeIMG4#6]
pc上好好的。android chrome 测试，加载 2.chunk.js 流量被劫了。加料后，不能压图片了。

不熟悉 webpack。

**Comment by think2011** [comment]
关于被劫持是怎么回事，能详细说说吗？


3个文件之所以分开因为在android就没必要加载IOS依赖的文件，IOS下没必要加载android的文件，PC同理来减少请求流量。

**Comment by wxt2005** [comment]
建议可以单独打包一个 Full Version 的文件。

**Comment by yuekcc** [comment]
我用的某通的 3g 网络，偶然会遇到异步加载 2.chunk.js 的时候被加上广告。具体就是加了一个 <script src=""></scrip> 标签。结果呵呵。

**Comment by think2011** [comment]
@yuekcc  关于劫持，可能你得从别的方面去解决，我用的也是联通，3G状态时不管我访问什么web内容，联通都会自动插入流量统计什么的功能。

**Comment by Cydmi** [comment]
我用RequireJS 引入  在配置依赖关系的时候,这样子配置的 <p> deps:['chunk1','chunk2'],
        exports: 'lrz'<p>,发现报这个错误Uncaught ReferenceError: webpackJsonp is not defined，webpack没了解过，请问这个有解决方法吗。

**Comment by think2011** [comment]
@Cydmi 不需要再额外写 deps.. 

`var lrz = require('lrz.bundle');` 即可，其他文件会按需加载的。
