### ISSUE TITLE
Boss，我发现一个问题，选择图片后，再打开选择窗口，然后取消选择会报错。【仅PC上有】

### ISSUE THREAD

**Issue by ihadai** [think2011/localResizeIMG4#7]
Boss，我发现一个问题，选择图片后，再打开选择窗口，然后取消选择，会报错：Uncaught Error: 加载图片文件失败。 【这是我在PC里测试的结果，手机里暂无该问题】

**Comment by think2011** [comment]
恩，谢谢，确实有这样的问题。

**Comment by xing139565** [comment]
有没有好的解决方法呢？比如我现在不需要上传多张图，只要穿一张图

**Comment by ihadai** [comment]
@xing139565    你要自己在  onchange 事件里的，  lrz  方法前 自己判断下数量。 如果超出了一个就  return。  就可以了。

**Comment by xing139565** [comment]
明白了，请教一下localResizeIMG3和localResizeIMG4区别在哪里呢，在性能以及兼容性方面哪个更稳定呢

**Comment by ihadai** [comment]
我在安卓手机里亲测： l3  生成一张3M左右的图片要15秒左右， l4 只要6秒左右。

**Comment by xing139565** [comment]
差距这么明显！那我还是用I4吧。。。

**Comment by think2011** [comment]
咦，Android不可能那么久吧，超过10秒都应该很过分了。

lrz4是在lrz3的基础上封装的，只是做了优化，理论上稳定性是差不多的。

**Comment by ihadai** [comment]
我是锤子手机，拍照后，确实要等 10秒以上， 但是同一个功能在苹果6 里最多2秒。

**Comment by think2011** [comment]
我试过iOS7的iPhone会卡住几秒钟，但是从没见过Android会那么久的。

如果现象是界面完全假死的话，那应该就跟Android本身有关了，这个没法解决。 

如果是其他原因那就好办了。

**Comment by ihadai** [comment]
应该是手机问题。

**Comment by simona1989** [comment]
发现一个问题，ios9上的qq，点击input没反应

**Comment by lijie1103** [comment]
在安卓手机上  onchang事件没有被调用

**Comment by wanzhe10** [comment]
大佬，我想问可不可以上传多张图片，我选择多张图片后只会显示最后一张

**Comment by xiaojiecong** [comment]
压缩了GIF图片，返回的base64图片格式是不是变成jpg了？
