### ISSUE TITLE
关于Lrz.prototype._getResize方法的疑问

### ISSUE THREAD

**Issue by windyrain** [think2011/localResizeIMG4#8]
您好think2011，我读到方法中的这段代码，有所疑问

    // 超过这个值base64无法生成，在IOS上
    if (ret.width >= 3264 || ret.height >= 2448) {
        ret.width *= 0.8;
        ret.height *= 0.8;
    }

此处是否应该为while,还是说图片的大小*0.8后就不会比3264大了

**Comment by think2011** [comment]
没太明白意思噢。

实测在IOS上，如果尺寸大于 3264 X 2448，就会出问题，所以只要宽高任意符合条件，那就缩小为原尺寸为80%。

**Comment by windyrain** [comment]
假设宽度是5000的话，5000*0.8=4000，然后就返回了

所以我想if是不是应该改成while
while (ret.width >= 3264 || ret.height >= 2448) {
    ret.width *= 0.8;
    ret.height *= 0.8;
}

**Comment by think2011** [comment]
@windyrain  啊，是的，你说的对！

**Comment by windyrain** [comment]
您的代码对我很有帮助！

很高兴，我的建议可以帮助到您，0.0！

**Comment by think2011** [comment]
resolved
