### ISSUE TITLE
为什么要乘以 0.8 ?

### ISSUE THREAD

**Issue by dd1994** [think2011/localResizeIMG4#9]
http://think2011.github.io/localResizeIMG4/test/ 

我看了下这个演示的源码有一行 `resultSize = toFixed2(rst.base64Len * 0.8 / 1024)` 这样就直接少了 20% 
啊，这样作弊不太好吧。。。。

**Comment by dd1994** [comment]
here http://think2011.github.io/localResizeIMG4/test/index.js?v=5151a0f

**Comment by think2011** [comment]
事实上实存后的图片会比预估的还小一些。

[在这里可以看到lrz3的demo，这个是有服务端处理过的](http://lrz3.herokuapp.com/demo/)

关于base64的算法规则没有弄明白，根据源文件和压缩后的大小对比，发现比例差不多是20%。

话说发送给后端的是base64而不是实际存的文件大小，确实表达不好，下次提交改正。
